### ISSUE TITLE
Terminal not showing

### ISSUE THREAD

**Issue by peterjuv** [lucaskenda/handyscripts#3]
Terminal stopped showing and scripts are not executed. Worked before, no idea what happened. Using Ubuntu 20.04.2 LTS, Kernel: Linux 5.8.0-50-generic, Architecture: x86-64. Using default settings, terminal is set to gnome-terminal. In shell, scripts and gnome-terminal work just fine.

**Comment by lparolari** [comment]
The same for me.

Don't know if this could help, but I have GNOME 3.36.8 installed.

**Comment by lucaskenda** [comment]
Hi!

You are in the wrong repo. Here is the issue: [https://github.com/lucaskenda/handyscripts2/issues/4](https://github.com/lucaskenda/handyscripts2/issues/4)

I've changed the terminal field so you can use another versions like:
**Gnome**: gnome-terminal --
**Tilix**: tilix -e
**KDE**: konsole -e

In order to fix the issue you must add in the field terminal "--" at the end.

![image](https://user-images.githubusercontent.com/4048688/116319465-f275d280-a78c-11eb-8796-d1667aec70a1.png)

**Comment by lparolari** [comment]
Thank you!
